### ISSUE TITLE
Destination not available

### ISSUE THREAD

**Issue by Djabx** [efficiosoft/btrfs-backup#18]
Hi,

I've got a laptop with Ubuntu 16.04.
I've got 2 devices:
* `/dev/sda1` in `/mnt/root` with 2 subvolumes `@` for the `/` and `@home` for `/home`.
* `/dev/sdb1` in `/media/abz/datalx/` where I would like to store my backup (in a directory `backup/home`).

I have a crontab for backup like that:

    /usr/local/bin/btrfs-backup -q -N 5 -n 10 -s /mnt/root/@home /media/abz/datalx/backup/home

My problem is when my second device `/media/abz/datalx` is not mounted (when I not on my desk) `btrfs-backup` create a directory on `/dev/sda1`.

How could I not send my bakcup if the device is not mounted ?
But I would like the snapshot being done in local (and send later).

**Comment by efficiosoft** [comment]
Hi,

I'd go the following route inside your crontab/anacron script:

1. Run ``btrfs-backup --no-transfer ...`` to just create the snapshot unconditionally.
2. Check if ``/media/abz`` is mounted. If yes, do ``btrfs-backup --no-snapshot ...``.

This should just be three lines of shell script or so.

Hope that helps.

Best regards
Robert

**Comment by Djabx** [comment]
Obviously that will do, but it would be very having this build in.

**Comment by efficiosoft** [comment]
How should btrfs-backup determine whether the right disk is mounted at the destination? You'd need to have an option to specify a directory to search for in /etc/mtab. Implementing the same check for remote storage is yet another story.

I currently think that I won't implement such an option, because it would be quite some effort for less benefit.

I'm now closing this issue, but you are welcome to continue discussion if you like.

Best regards
Robert
