### ISSUE TITLE
ioctl(BTRFS_IOC_TREE_SEARCH, subvol_id 359) ret=-1, error: Operation not permitted

### ISSUE THREAD

**Issue by ktiedt** [efficiosoft/btrfs-backup#20]
After the other error was fixed, I now seem to get this error, same setup, I see the target directory created on the remote server and then this failure.
```
At subvol /home/user/lib/snapshot/20180418-002105
ioctl(BTRFS_IOC_TREE_SEARCH, subvol_id 359) ret=-1, error: Operation not permitted
ERROR: cannot resolve our subvol path
00:22:44  [ERROR]  Error during btrfs send / receive
```

Note: both servers were updated to 0.3.1 prior to testing.

**Comment by efficiosoft** [comment]
Well, I can't really see what's causing the issue without having the exact options you invoked btrfs-backup with, but this one clearly is a permission problem. I guess that you don't log in as root at the remote server. Either do so, or configure sudo to not require a password for executing ``/bin/btrfs`` for that particular user and use the ``--ssh-sudo`` flag of btrfs-backup.

This is not a fault of btrfs-backup, it's rather a property of btrfs to not allow regular users to receive subvolumes, because the received stream could contain files that would normally not be readable/writable by that user due to permissions.

**Comment by efficiosoft** [comment]
Maybe btrfs will get a mechanism to mitigate the problems with receiving snapshots as non-root users in the future, but afaik it's not possible at the moment.

**Comment by efficiosoft** [comment]
This just as a reference, but for receiving the same reasons apply I think.

https://www.spinics.net/lists/linux-btrfs/msg63954.html

**Comment by ktiedt** [comment]
Ah it's probably the ssh-sudo flag, I don't use root but did enable passwordless sudo btrfs for that user. Will confirm this evening. Thank you for the help!

**Comment by ktiedt** [comment]
Genius @efficiosoft - somehow I completely missed that flag when reading up on the process, I now have snapshots working remotely.

Great work!

**Comment by efficiosoft** [comment]
No problem and thanks for using btrfs-backup, good to hear that it's working now.

Best regards
Robert
